### PR TITLE
API changes, unittest, and docs

### PR DESCRIPTION
**Pull request by vincentdephily**
This PR gathers various API-breaking changes together for an eventual 0.2 release. It's a work in progress, I'm looking for feedback. It's based on previous non-API-breaking commits that have yet to be merged into master; just look at the "refactor" commits.

- The String -> Vec<u8> changes are required to match the spec.
- The NonZeroU16 and QosPid changes prevent big gotchas.
- The rest are improvements to usability, code layout, and docs.

I've got a few other things in mind (more buffer size checks, s/PacketIdentifier/Pid/...), but this looked like a good stage for a review. I'll be dogfooding these changes soon, in a test server and a production client.

Cheers.

### CODE REVIEW

**Comment by 00imvj00** [comment]
Awesome. Looking forward to the changes. Please ping me once this PR is out if WIP status. @vincentdephily

**Comment by 00imvj00** [comment]
Are you trying to standardize based on some trait extension? I was thinking about doing that way.

sort of like creating `MqttRead` and `MqttWrite` traits which will extend `Read` and `Write` std traits.

Let me know your thoughts.

**Comment by vincentdephily** [comment]
For the moment I'm quite happy with the `encode()/decode()` functions, as they're very straightforward to use as a tokio `Codec` for the `FramedRead/FramedWrite` APIs.:

```rust
pub struct Codec;
impl Decoder for Codec {
    type Item = mqttrs::Packet;
    type Error = std::io::Error;
    fn decode(&mut self, src: &mut BytesMut) -> Result<Option<Self::Item>, Self::Error> {
        mqttrs::decode(src)
    }
}
impl Encoder for Codec {
    type Item = mqttrs::Packet;
    type Error = std::io::Error;
    fn encode(&mut self, item: Self::Item, dst: &mut BytesMut) -> Result<(), Self::Error> {
        mqttrs::encode(&item, dst)
    }
}
```

In a different project I'm actually using the `mqtt-rs` crate which uses extension traits, and it's not as convenient for my use case.

That doesn't mean that extension traits aren't a good idea, they're just not on my radar at the moment. We could indeed provide helpers for various environments, but we need to define them first (tokio, std, no_std, asyc/await....) and make sure that there's a demand for it.

The encode/decode functions as they currently stand are pretty composable and should be easy to use in most architectures. The main thing you can't do with them is continuations (finish parsing where you left off if there wasn't enough data), but I doubt it would be worth it, as MQTT is very simple and re-parsing is probably cheaper than the complexity of continuations.

Right now I'm trying out these changes on my unittesting-server project (which I hope to opensource at some stage), and there's a bit of friction around the `PacketIdentifier` type, so I make tweak the API a bit. Eventually I'd like to also convert my `mqtt-rs`-based client to `mqttrs`, which will provide a different usability datapoint.

**Comment by vincentdephily** [comment]
On change that could be nice, even if just a convenience :
```rust
pub fn encode(packet: impl Into<Packet>, buffer: &mut BytesMut) ...
impl Into<Packet> for Connect ..
impl Into<Packet> for Subscribe ..
impl Into<Packet> for Publish ..
```

**Comment by vincentdephily** [comment]
I'm going to call the API changes done, unless I find issues while dogfooding or you have some concern to raise. I'll write a changelog and some docstrings tomorrow.

**Comment by 00imvj00** [comment]
At this point. No. may be in future before 1.0 release. as we might add v5 support for mqtt. i still need to read the spec.

**Comment by vincentdephily** [comment]
Sorry, I'm not sure what you're saying "no" to ? You have no concern to raise about these API changes ? You do not want to merge yet and prefer to evaluate MQTT5 first ?

I'd like to support mqtt5 too, but that should IMHO be kept for a later API-breaking release (hopefully much less breakage than this branch). As for what'll deserve a 1.0 version, probably mqtt5 and some adapters/examples/doc. Would be nice to associate a milestone with some issues in github.

In the meantime, found my first dogfooding issue: `tokio::codec::Encoder` requires `impl From<io::Error> for mqttrs::Error`. Easy, but I want to double-check that we still get nice `mqttrs::Error`s out.

**Comment by 00imvj00** [comment]
I meant NO in terms on i don't have any concerns to raise :) 

And yes, as you suggested in above comment, that plan looks perfect.

**Comment by vincentdephily** [comment]
I think this PR is ready, hope you like it. There's more API changes we might want to do, but this PR is big enough already, it's probably best to let the API rest for a while. I'm using this branch server-side, and will start using it client-side soon.

**Comment by 00imvj00** [comment]
Yup, looks good. Please merge it.

**Comment by vincentdephily** [comment]
I don't have write access to your repo. Either click "merge" yourself or give me write access :)

**Comment by 00imvj00** [comment]
You want me to tag this commit as `0.2.0` release? as you made api changes it make sense.

**Comment by vincentdephily** [comment]
Yes I'd say so, let's release a 0.2.0 :)

I have a few more API-breaking changes in mind, but it's probably a good idea to use 0.2 for a while to get a clearer idea of what should be in 0.3. I don't think this crate is used much yet, but I'm looking forward to people having a look at this iteration.

**Comment by 00imvj00** [comment]
awesome. I have tagged as 0.2.0 and also pushed 0.2.0 release in crates.io.
also created milestone 0.3.0.

**Pull request merged**
