### PR TITLE
Make alloc optional, defaulting to slice based API

### LINKED ISSUE #27: Support alloc-free operation
Split off from discussion in #16. The next step after no_std is supporting no_alloc.

I think the key ingredient will be to switch encode()/decode() to use a BufMut/Buf trait exclusively without relying on a BytesMut/Bytes implementor. That would enable no_alloc users to pass a `[u8, N]` instead of a Bytes, and we can let them deal with buffer_too_small errors.

I've already done a partial switch to the Buf/BufMut traits, but the final bits are tricky. Might be worth checking with upstream why some of the useful functions are implemented on the Struct instead of the trait.

### PR DESCRIPTION
**Pull request by MathiasKoch**
Currently all Bytes/BytesMut are eliminated, but some simple slice tests are still needed.

Also we need to figure out how we want to setup tests.. We could just test with `--all-features`, but i think that would never catch `no_std` and `no_alloc` bugs.. On the other hand, testing without default features, wouldn't allow prop-tests and `Bytes/BytesMut`, so we probably need to do tests in two steps, or something like that?

All tests pass in the current configuration.

After this, `alloc::{Vec, String}` has to be addressed.

Fixes #27

### CODE REVIEW

**Comment by MathiasKoch** [comment]
> This needs updated (or additional) tests that decode into a stack-based buffer.

I will definitely add some tests and rewrite some of the existing, but this is still just a draft PR, in order to get some discussion on the implementation details going.

> Can you fix the git comment ? Missing some key words, maybe shell expansion got you.

Ohh sure, i used backticks '`', which is apparently not allowed in git messages.. I will amend it.

> If I understand this 2nd commit correctly, it expands just one unittest and fixes function signatures to take a mut buf everywhere ?
>
> Were the signature changes required to make the unittest compile, or are they forward-planning for n upcoming change ?

The signature changes are not super necessary, but they are changed because it is the correct way of using an `impl trait` signature.. The `&mut impl trait` doesn't really make sense, and i think the only reason it works with Bytes/BytesMut, is because of their internal `Deref`implementations. With almost all other types, it makes for a very awkward combination of ampersands and `mut` keywords. Also it doesn't enforce that the variable passed to the interface is marked as mut.


We still need to address how to rid the current `alloc::String` and `Vec`, without making the changes too intrusive..

**Comment by vincentdephily** [comment]
> I will definitely add some tests and rewrite some of the existing, but this is still just a draft PR, in order to get some discussion on the implementation details going.

No worries. I just like to see the tests early for a change like this, helps me see that the API is still sound.

> Ohh sure, i used backticks '`', which is apparently not allowed in git messages.. I will amend it.

Backticks are allowed and useful, they might just have been interpreted by your shell before sending the message to git. Either escape them, or use a text editor for your commit message.

> The signature changes are not super necessary, but they are changed because it is the correct way of using an impl trait signature.. The &mut impl trait doesn't really make sense, and i think the only reason it works with Bytes/BytesMut, is because of their internal Derefimplementations. With almost all other types, it makes for a very awkward combination of ampersands and mut keywords. Also it doesn't enforce that the variable passed to the interface is marked as mut.

Ok, makes sense, thanks. Let's see how it pans out with the other changes done.

> We still need to address how to rid the current alloc::String and Vec, without making the changes too intrusive..

In theory the `String`s and `Vec<u8>`s should get converted to slices. This'll make lifetimes more cumbersome, but if `decode()` takes the buf by ref and returns a consumed usize (or moves the buf and returns two buf slices), it should work.

Note that I really don't want to break compatibility with tokio's `tokio_util::codec::Framed` API. At the moment we can simply

```rust
struct MqttCodec;
impl Decoder for MqttCodec {
    type Item = Packet;
    type Error = mqttrs::Error;
    fn decode(&mut self, src: &mut BytesMut) -> Result<Option<Self::Item>, Self::Error> {
        mqttrs::decode(src)
    }
}
impl Encoder<Packet> for MqttCodec {
    type Error = mqttrs::Error;
    fn encode(&mut self, item: Packet, dst: &mut BytesMut) -> Result<(), Self::Error> {
        mqttrs::encode(&item, dst)
    }
}
```

It's ok if the noalloc changes make this a little bit more complicated (we might even provide this boilerplate behind a feature flag), but it shouldn't make it less efficient.

There are also a handful of `Vec<StringOrStruct>` in the returned packets (for example `{Un,}Subscribe.topics`, and AFAIU MQTT5 will have a lot more of those) and I'm really not sure how to handle those. One option would be using something like a SmallVec that isn't allowed to spill to the heap (and therefore has a max capacity and may cause an error during decoding in noalloc mode), but it's not super satisfying (having to guess at the spill threshold, adding a dependency, adding a failure mode...).

**Comment by MathiasKoch** [comment]
- Fixed the backticks in the git message
- Rewrote all the decoder tests to use &[u8], as these will never allocate anyways
- Rewrote the encoder tests to test on both &mut [u8] and BytesMut
- Added a test to verify the behaviour of Error::WriteZero in case the input buffer is too small in encode, and also verifies that alloc types (BytesMut), allocates and returns correctly.

I have not made any changes to the codec_tests, as i feel a bit unsure on the prop_test stuff.. 
Btw, is there a reason why decoder.rs contains tests as well, rather than just keeping them in decoder_test.rs?

> Note that I really don't want to break compatibility with tokio's tokio_util::codec::Framed API. At the moment we can simply

Cool, i don't see how that becomes a problem.. I can add the trait impl behind a feature flag, and add a unit test to make sure we don't break this, if you would like?

I think we should be able to manage the input part of Vec and String with slices and lifetimes, but the returns are a bit harder..? Also that would mean different types for input and returns, which i think would be a bit sad.. 
I think this part is the harder part of allowing no_alloc, so any suggestions on ridding string and vec is greatly appreciated!

**Comment by MathiasKoch** [comment]
I am still battling a bit with how to eliminate `Vec` & `String` as part of this feature, on the side of all my other work.

I do really want to see this happen though, as we are basing our entire product-line with this as a core crate, and we see it as a strict requirement to eliminate run-time allocators, as 100% uptime and predictable memory outcomes is important for us. 

Do you have any idea on how to combat these? Right now, we are considering forking internally to rid the requirement of not breaking the API, and thus allowing us to replace it all with something like `heapless`. But i would much rather if we could figure out a way to get this upstream into this crate!

I can add something like `heapless` with generic lengths and a sensible default value on each of them, eg.

```rust
/// Connect packet ([MQTT 3.1]).
///
/// [MQTT 3.1]: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718028
#[derive(Debug, Clone, PartialEq)]
pub struct Connect<
    C = consts::U128,
    U = consts::U128,
    P = consts::U128,
    T = consts::U128,
    M = consts::U128,
> where
    C: ArrayLength<u8>,
    U: ArrayLength<u8>,
    P: ArrayLength<u8>,
    T: ArrayLength<u8>,
    M: ArrayLength<u8>,
{
    pub protocol: Protocol,
    pub keep_alive: u16,
    pub client_id: String<C>,
    pub clean_session: bool,
    pub last_will: Option<LastWill<T, M>>,
    pub username: Option<String<U>>,
    pub password: Option<Vec<u8, P>>,
}
```

With more sensible defaults of course. I don't think its pretty, but it allows using `Connect` without explicitly specifying the generics, while still allowing to overwrite them in case a user is not happy with the initial max-length limitations.

**Comment by 00imvj00** [comment]
How about just one allocation per packet?? I tried hard, but I think we can achieve that with one allocation easily. 

The idea is, store the whole package as a stream of bytes inside `Packet`, then call methods to convert those bytes to appropriate fields.

This seems like a viable option to provide some consistency in allocation. 

Another option is to receive vector from outside and then own it,  but that also requires allocation outside.

```
encode(&mut buffer: u8[], internal: Vec<u8>)
```
what above function will do is, it will copy single packet length bytes from buffer into internal vector and then own it. 

This was the closest i came to keeping it clean as well as minimal allocation design.

**Comment by MathiasKoch** [comment]
I think that could work, if it would be possible to pass in the `internal` as a `&mut [u8]` instead, maybe something like
```
encode_slice(&mut buffer: u8[], internal: &mut [u8])
encode(&mut buffer: u8[]) {
    ...
    encode_slice(buffer, ..)
}
```
To allow alloc users to have automatic allocation?

another option to `&mut [u8]` would be `impl BufMut`?

**Comment by 00imvj00** [comment]
Yes, this can also work. if you can experiment with this and post if this is viable option.

**Comment by MathiasKoch** [comment]
I can try, but i think 

> The idea is, store the whole package as a stream of bytes inside Packet, then call methods to convert those bytes to appropriate fields.

Is the part i will find a bit tricky atm.

**Comment by 00imvj00** [comment]
Not at the point. 

So, I will tell you the idea.

Instead of parsing in advance, we will store the stream of bytes received from the socket as it is.

Once, someone call `Packet.qos()`, we can parse stream and get only Qos Part. 

Sort of like lay parsing. This might also save us CPU as we are doing eager parsing.

**Comment by MathiasKoch** [comment]
Ahh.. I think that makes great sense! 
I will try to give it a shot during the coming week.

**Comment by jordens** [comment]
There is [managed](https://crates.io/crates/managed) (used heavily in smoltcp) to abstract over heap/stack ownership. But I don't know whether it helps here.

**Comment by MathiasKoch** [comment]
After having a small look at this, i am not convinced it is something i can do at the moment. This would be a COMPLETE rewrite of the crate.. It might even be faster to start from scratch...

> Once, someone call Packet.qos(), we can parse stream and get only Qos Part.

This would mean that all the `Packet`s (`Connect`, `Subscribe`, etc.) cannot be structs holding data, as there are nothing but an internal byte buffer, until one calls a method on the packet.. 

So basically neither the implementations of the crate, nor the definitions of structs would be reusable?

**Comment by 00imvj00** [comment]
@MathiasKoch yes. this might require lots of changes. You can experiment, if all goes good we can version bump. 

But, are you positive about the idea?? if yes, we can experiment atleast and see how it pans out.

**Comment by MathiasKoch** [comment]
It just turned out to be a larger change that i anticipated.

That said i DO think it could work out, and also with a lot of benefits over the current approach, both in regards to alloc-free, but also the lay parsing, and one step closer to zero-copy.

I think the first problem would be to work out what the API from a user facing side would look like.. 

I think the entire encode part would be okay as-is? assuming we change the structs it uses, to be slice based instead, for topic names, client id etc., as that would mean the full encode half of the crate would be alloc-free, and actually also closer to zero-copy..

So it's the decode half that needs to rewritten somehow. The sad part is that the decode half wouldn't be able to use the same structs as the encode, but i guess that can be somewhat fixed by implementing `From` across everything, and using a lot of `Into<>` trait bounds?

**Comment by 00imvj00** [comment]
Yes, even I was thinking about `From` and `Into`.

If not, we can have decode something like.

```
let mut packet = Packet::new();
let buffer = [u8;];
fn decode(&mut buffer, &mut packet);
```

here, we are creating a packet outside only, which will perform required single allocation.

After that, we will copy the required buffer slice from buffer into the packet. 

This is also, if we can somehow use `Into`.

**Comment by MathiasKoch** [comment]
So looking at all t he packet structures here: https://gist.github.com/rust-play/24e7959550a98cd1d507a881f02c5e60

How would we divide the lifetimes? I have now put the exact same lifetime on everything, which is outright wrong, but i am not sure how it should look...?

**Comment by 00imvj00** [comment]
I was thinking of instead of storing references, we will be storing offset and length. So, for the topic, we can store (5, 10), so, from 5th byte to 10 bytes. then we can convert that into a string, on-demand. 

So, technically we are just storing (offset, length) combo for all string. In that, we will not have to allocate. At the same time, no lifetime will be required, as this is not a reference.

What are your thoughts?

**Comment by MathiasKoch** [comment]
Aha..
I guess that could work.. So something like

```rust
#[derive(Debug, Clone, PartialEq)]
pub struct Connect {
    // Fixed length variables, shouldn't need the length part
    protocol: usize,
    keep_alive: usize,
    client_id: (usize, usize),
    clean_session: usize,
    last_will: Option<(usize, usize)>,
    username: Option<(usize, usize)>,
    password: Option<(usize, usize)>,
}

impl Connect {
    pub fn protocol(&self, buffer: &[u8]) -> Protocol {
        Protocol::from_buffer(&buffer[self.protocol..self.protocol + 1])
    }

    pub fn keep_alive(&self, buffer: &[u8]) -> u16 {
        ((buffer[self.keep_alive] as u16) << 8) | buffer[self.keep_alive+1] as u16
    }

    ...
}
```

I like the idea, but i am not sure i like having to pass in the buffer get a field value.. Can we somehow remove that argument?

**Comment by 00imvj00** [comment]
Encode doesn't have to be this way, as in encode, we are already creating byte-stream out of fields. 

The issue of allocation only comes with decoding.

**Comment by MathiasKoch** [comment]
I agree, but in that case i think the fields from above, with the lifetimes could probably be used for the encode part, as we still need to rid String and Vec from those..

And if that is the case, we might as well just use them for decoding also, storing references to the buffer..

Something like 
```rust
#[derive(Debug, Clone, PartialEq)]
pub struct Connect<'a> {
    pub protocol: Protocol,
    pub keep_alive: u16,
    pub client_id: &'a [u8],
    pub clean_session: bool,
    pub last_will: Option<LastWill<'a>>,
    pub username: Option<&'a [u8]>,
    pub password: Option<&'a [u8]>,
}

impl Connect {
    pub fn from_buffer(buffer: &[u8]) -> Result<Self, Error> {
        let header = ...;
        ..
        Ok(Connect {
            ..,
            client_id: &buffer[4..17],
            username: Some(&buffer[26..29]),
            ..
        })
    }
}
```

I think that should give the same number of allocations? The only performance hit would be reading the header (probably needed anyways), and "parsing" primitive types (not expensive at all)?

**Comment by 00imvj00** [comment]
Yes, this also works. I was thinking the same. because both are the same. but the above snippet might look better. 

I think we should go with that.

**Comment by 00imvj00** [comment]
I honestly like the last suggestion you gave better. let's see if we can achieve that.

**Comment by MathiasKoch** [comment]
Okay, i will try to give it a swing, and see if i can make the decode part work as well!

**Comment by 00imvj00** [comment]
👏 

Apart from this, @MathiasKoch do you think we should have discord or something where we can have conversations and idea-sharing??

**Comment by MathiasKoch** [comment]
That way we can also still do 
```rust
pub fn decode_slice<'a>(mut buf: impl Buf, memory: impl BufMut) -> Result<Option<Packet<'a>>, Error> {
    ...
}

#[cfg(feature = "alloc")]
pub fn decode<'a>(mut buf: impl Buf) -> Result<Option<Packet<'a>>, Error> {
    let memory = BytesMut::new();
    decode_slice(buf, &mut memory)
}
```

**Comment by MathiasKoch** [comment]
I think that would be great.. I can be found on Matrix already, maybe that could work? Seems like a preferred place for at least the embedded community of rust..

@mathias_koch:matrix.org

**Comment by MathiasKoch** [comment]
@00imvj00 

As promised i took a swing at it, so please have a look, to see if this is somewhat what you had in mind..

Left to do:
- [ ] Suback::new()
- [ ] Unsubscribe::new()
- [ ] Subscribe::new()
- [ ] Fix proptests
- [ ] Helper functions for alloc version

The three `new()` functions needs a proper way of converting from structured data slices, eg `topics: &'a [SubscribeTopic<'a>]` to the encoded `&[u8]` version held internally.

Regarding the proptests, they still don't support borrowed data in their strategies (Packet now has a lifetime). See https://github.com/AltSysrq/proptest/issues/9
Not sure what to do about it, other than comment it out and wait for them to fix the issue?

This is a breaking change due to:
- Changed definition of packet structs (borrowed data instead of owned).
- Missing `decode()` function, (introduced a new `decode_slice()` function), but the old `decode()` should be maybe be possible to make, to ease the transition for alloc/std users (The aforementioned helper functions). 

Regarding the remaining points, i could use some suggestions on how to solve them..

**Final note**:
`decode_slice()` will not "eat" the buffer, as `decode()` did, so a call to `decode_slice()` will leave the passed in buffer intact, and the result will be referenced to it, so it cannot be dropped or cleared as long as the resulting packet exists. Perhaps we should aim for some kind of double buffer system, with a function to copy a single packets bufferstream into a new buffer, that can be fed into `decode_slice()`?

**Comment by 00imvj00** [comment]
Yes, I will have a look, and let you know.

**Comment by MathiasKoch** [comment]
After looking a bit more at this, i actually think this approach also fixes the decoding part of #18 as the decoding is now fully zero-copy..

**Comment by MathiasKoch** [comment]
I added a function (currently called `clone_packet`, i have no feelings towards naming), that does exactly this.. It will skip bytes in the buffer until it finds a valid header, then it will read the header, and copy the bytes from the input buffer to the output buffer, and then advances the input buffer.

The only thing missing from this approach is automatically sizing the output buffer, if alloc is available? not sure how, but maybe it could be done using BufMut instead of byte slice?

**Comment by MathiasKoch** [comment]
I now also have this working in my nostd MQTT client, now completely alloc-free.

I still need to fix the ` Suback::new()`, `Unsubscribe::new()`, `Subscribe::new()` somehow, but i think that is the last remaining functional issue, before correcting the docs. Any suggestions on how to handle these constructor functions?

**Comment by MathiasKoch** [comment]
I fixed the `Suback::new(), Unsubscribe::new(), Subscribe::new()` functions, by introducing `heapless` as a new dependency. It is not perfect, but i couldn't find any other way of doing it, as it requires at least one allocation no matter how.

I chose to set a limit (currently 5), on how many topics it is possible to subscribe and unsubscribe to in a single packet, if std is not available. I think this is very reasonable, given that it is only applicable in no_std contexts.

**Comment by MathiasKoch** [comment]
Found one last bump on the road: https://github.com/tokio-rs/bytes/blob/a3304e8b8b74e2d5260d8419b6d8075e004e4c39/src/lib.rs#L84

Any suggestions? Or any reasons to stick with the bytes dependency, as it is purely used for the BufMut trait now? Would make sense to find a similar dependency more suited, or an alternative all together? We could rewrite the encode part to the same `buf: &'a mut [u8], offset: &mut usize` format, with a helper function taking a `BufMut` in case `alloc` is available? That would also give a fully consistent API wrt. encode/decode being the same.

**Comment by 00imvj00** [comment]
@MathiasKoch any updates on changes requestd?

**Comment by MathiasKoch** [comment]
@00imvj00 Changes requested? 

You mean the ones @vincentdephily made 14 commits ago? They were addressed in the first of said 14 commits.. But if you read my comments, there is some stuff up for discussion.

**Comment by MathiasKoch** [comment]
What can we do to bring this forward? I have been running it in production for quite some time now, with no issues at all, and i think especially the zero-copy properties of this PR is really nice!

**Comment by 00imvj00** [comment]
@MathiasKoch merged. thanks. !!

**Comment by 00imvj00** [comment]
Should we bump the verison? @MathiasKoch

**Comment by MathiasKoch** [comment]
@00imvj00 Yeah, i would do so, as it might bring unforeseen breaking stuff.. Better safe than sorry

**Comment by MathiasKoch** [comment]
@00imvj00 Can you also release 0.4.0 to crates? :) Thanks man!

**Comment by 00imvj00** [comment]
yeah, will release it in crates by tomorrow.

**Comment by 00imvj00** [comment]
@MathiasKoch i think adding lifetimes in packet adds more complexity when wiriting `async` code in rust. I think we might have to come up with alternative, innovative solution. 

The bottomline is, we want to only do single allocation per packet and we don't want to use lifetimes.

Can we achieve something like this?

I am leaning towards the idea of (offset, length) storage. i know it is bit not simple, but i think we can achieve the goals with that, i will try to come up with impl for that. 

Apart from that, we might also want to get rid of `BytesMut` dependency.

We can try to have our own trait like `MqttRead: Read`, `MqttWrite: Write`, which users of the lib will have to implement, we will take care of all the moethods internally. Users will just have to write the declaration. 

thoughts? @vincentdephily

**Comment by MathiasKoch** [comment]
Ahh, yeah i did not think about `async`.

I would be sad to see something like `MqttRead: Read`, `MqttWrite: Write` though, as `Read` / `Write` is not available in `#[no_std]`.

That said i think it should be possible, but would probably take a look towards some of the bigger libraries that support `no_std`, `no_alloc` and still supports `async` fully, for their implementation details?

**Comment by 00imvj00** [comment]
Yeah. that would be great.

One of the thing we totally missed was `async`. Today I started working on demo programs and there was wired lifetime issue, and It stuck, it is killing the ergonomics of the whole thing and making it as wired as it was before. 

I think we might have to push towards ease of use also. 

If we can crack this right, we can easily apply this method to all sorts of wired protocols.

**Comment by MathiasKoch** [comment]
Can you bring a snippet of async code where this poses an issue? Just to make sure we are actually addressing the same issue :)

**Comment by 00imvj00** [comment]
@MathiasKoch sure i will. I think the issue is happening due to lifetime parameter in the Packet type. We need a way to get rid of that. I think i have figured out a way. not pretty. but will work. experimenting on that.

**Comment by stabler** [comment]
The lifetime change is breaking my code! I can't pass `Packet` across threads anymore.

At minimum, can we add an owned version of the packet, and API to convert between the two (similar to Cow)? Or is there another way to manipulate owned `Packet` objects that I'm not seeing?

**Pull request merged**
